In [1]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [2]:
x = np.array([[-1, -1], [-1, 1], [2, 1], [3, -2]])
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(x)

In [3]:
distance, indices = nbrs.kneighbors(x)

In [4]:
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 2]])

In [5]:
distance

array([[0.        , 2.        ],
       [0.        , 2.        ],
       [0.        , 3.        ],
       [0.        , 3.16227766]])

In [6]:
from sklearn.neighbors import KDTree

In [9]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
kdt = KDTree(X, leaf_size=30, metric='euclidean')
kdt.query(X, k=2, return_distance=True)

(array([[0.        , 1.        ],
        [0.        , 1.        ],
        [0.        , 1.41421356],
        [0.        , 1.        ],
        [0.        , 1.        ],
        [0.        , 1.41421356]]),
 array([[0, 1],
        [1, 0],
        [2, 1],
        [3, 4],
        [4, 3],
        [5, 4]]))